### ISSUE TITLE
Instances behind ASG

### ISSUE THREAD

**Issue by amirmb** [aws-solutions/instance-scheduler-on-aws#15]
Is it possible to de-attach and re-attach instances are behind ASG based on scheduled action?

**Comment by arieleeuw** [comment]
Hi,

As ASG have their own scheduling for the # of instances in the group, we do not support this from this solution. ASG is really built around the concept of creating new instances on demand, where Instance Scheduler uses (re-)starting/stopping instances for applications that were not designed to leverage Auto Scaling.

Hope this makes the difference between both more clear.

**Comment by DanielRedOak** [comment]
I think there is still a use case around handling start/stop of ASG instances.  We have some instances that take awhile to provision but are still in an ASG to deal with failure. Scheduling the ASG to scale down would work but changes to the instances that the QA folks were doing would be lost and the time for those instances to scale up would be a hit. Perhaps suspending/un-suspending  the termination process during the scheduler action would be a decent compromise. I may give this a try locally and see how it goes.

**Comment by amirmb** [comment]
Hi Daniel,
I agree with you, I have started that path as well as the application deployment for ASG instances is taking long enough i my scenario to consider scaling up/down solution.
I would like to see how you are getting with this.

**Comment by DanielRedOak** [comment]
It's relatively straight forward. I am thinking that the right way to handle the stop would be in combination with putting the instance in standby in the ASG. That way it would go through pending and back into service when the instance it re-enabled. If you have other thoughts on this let me know.

**Comment by DanielRedOak** [comment]
Here is the branch where I pushed the work: https://github.com/DanielRedOak/aws-instance-scheduler/tree/SRE-8675 Things should be mostly complete and it handles failure as gracefully as we can.

- When doing discovery on instances, if they belong to an ASG the name of the ASG is added to the instances attributes
- If an instance is scheduled to be stopped and is in an ASG, first we call the API to put it in StandBy mode. If it fails, the instance is removed from the stopping_instances so that the scheduler will not stop it while it is still in the ASG. 
- If an instances is scheduled to be started and is in an ASG, it will start first, then attempt to put the instance InService. If the call to put the instance InService fails, a warning is logged but no other action is taken since we were able to start the instance.
- The batching generator was modified to allow sending back of instances for individual retries
- Batching is used for Enter/ExitStandby calls. If the batch fails, the instances are sent to the batching generator and retried individually so we can try our best to Enter/Exit Standby mode for instances and Start/Stop them

**Comment by DanielRedOak** [comment]
@arieleeuw I thought I commented but it seems to not be here now. Anyways, let me know how this looks and I can open a PR and work on getting it merged in!

**Comment by DanielRedOak** [comment]
We've been running this for awhile now and things are working great. I additionally had to make some changes to make things work with KMS encrypted boot volume instances. Let me know if you'd like to turn my work into a PR.

**Comment by arieleeuw** [comment]
Daniel, yes thanks for your feedback on the KMS issue. I've passed this to our technical writers to be included in the documents as a required step when using these keys.
If you think there is more info missing feel free to leave feedback through the link in our online documentation so we can improve it.
Thanks,
Arie

**Comment by arieleeuw** [comment]
We're considering to have ASG instances support in future releases.

As ASG already has it's own mechanism for [scheduling](https://docs.aws.amazon.com/autoscaling/ec2/userguide/schedule_time.html) we did not give this the highest priority yet, as it also could confuse customers. Instance Scheduler was initially developed for customers running applications that were not designed for autoscaling and horizontal scaling.

**Comment by DanielRedOak** [comment]
@smitaskamat just to circle back on this, we've been using my branch since I opened the PR with great success so it should be relatively stable.

**Comment by noobianz** [comment]
Daniel,  I was taking a look at  this as I would like to handle the start/stop of ASG instances via the scheduler.  I'm having difficulty building from the SRE-8675 Branch, No issues with the master branch.  Any help/advice you can offer on what I'm doing wrong would be much appreciated.  I get the error below when I run the build script.

build main template
python ./build-instance-scheduler-template.py ../cloudformation/instance-scheduler.template  `cat version.txt` solutions aws-instance-scheduler/latest/ > ../../deployment/instance-scheduler-`cat version.txt`.template
Traceback (most recent call last):
  File "./build-instance-scheduler-template.py", line 34, in <module>
    main(template_file=sys.argv[1], version=sys.argv[2], bucket=sys.argv[3], prefix=sys.argv[4])
  File "./build-instance-scheduler-template.py", line 30, in main
    template = get_versioned_template(template_file, version,bucket, prefix)
  File "./build-instance-scheduler-template.py", line 26, in get_versioned_template
    return json.loads(template_text, object_pairs_hook=OrderedDict)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 789 column 39 (char 26451)
make: *** [cfn] Error 1

**Comment by TamerElfeky** [comment]
The same error by @noobianz

**Comment by TamerElfeky** [comment]
@noobianz  Just add the  curly brackets {} around Fn::Join  in instance-scheduler.template line 789
                        "Resource": [
                            { "Fn::Join":[
                                ":", [
                                    "arn:aws:kms", {
                                        "Ref": "AWS::Region"
                                     }, {
                                        "Ref": "AWS::AccountId"
                                    },
                                    "key/*"
                                        ]
                            ]
                        }
                        ],

**Comment by kapilt** [comment]
fwiw, cloudcustodian.io  supports asgs, rds, redshift, ec2 etc for off hours functionality for several years, if folks want something opensource, actively developed, well tested, with these features today.

**Comment by rakshb** [comment]
Hello,
ASG service already supports the scheduling feature (https://docs.aws.amazon.com/autoscaling/ec2/userguide/schedule_time.html), so this is not currently on our roadmap. We will keep the request open however to receive customer feedback. If there is enough interest in having this feature in instance scheduler we will reconsider putting it on the roadmap

**Comment by rakshb** [comment]
Hello,
ASG service already supports the scheduling feature (https://docs.aws.amazon.com/autoscaling/ec2/userguide/schedule_time.html), so this is not currently on our roadmap. We will keep the request open however to receive customer feedback. If there is more interest in having this feature in instance scheduler we will definitely reconsider putting it on the roadmap

**Comment by herwindo** [comment]
hi @rakshb we do understand that ASG can be configured to have scheduled actions, but the selling point of AWS Instance Scheduler is its consolidated place where you can handle both RDS and EC2 instances. Using scheduled actions defeats the purpose of using this tool. Hope this can be sorted out soon

**Comment by danielesalvatore** [comment]
+1

**Comment by rdonkin** [comment]
The gap I found with built-in ASG scheduling is that it doesn't take account of local time including daylight saving time (DST) - so you have to adjust the schedules twice a year unless being out by one hour is OK. (Same with Linux crontabs, though systemd at least is local time aware.)

https://cloudcustodian.io looks quite impressive, supports ASGs and does more than scheduling - thanks @kapilt for mentioning.

**Comment by panneer-subramanian** [comment]
+1

**Comment by nawazxy** [comment]
2021 and we still don't have this feature

**Comment by ismail44** [comment]
My use-case for including ASG would be when deploying into a dev or other non-prod environment. Adding "Schedule" tags to these instances would only cause the ASG to spin up (continually) more instances when the scheduler shuts down during "off-hours". My solution was simple enough to have the scheduler alter the Desired Capacity during off/on hours.

**Comment by jiba21** [comment]
+1

**Comment by rakshb** [comment]
This feature request has been prioritized in our backlog for a future release.

**Comment by CrypticCabub** [comment]
ASG Scheduling is now supported in [v3.0.0](https://github.com/aws-solutions/instance-scheduler-on-aws/releases/tag/v3.0.0)
