### ISSUE TITLE
Support Elastic Container Service (Amazon ECS)

### ISSUE THREAD

**Issue by cbanciu667** [aws-solutions/instance-scheduler-on-aws#160]
Hi,

Is there anything planned to handle ECS clusters and its ASGs ?
I worked on something similar in the past (see attachment). Maybe it can be used as inspiration.
[ecs-asg.py.txt](https://github.com/awslabs/aws-instance-scheduler/files/4484789/ecs-asg.py.txt)

**Comment by gockle** [comment]
@cbanciu667 thank you for the input, this will be taken up as a new feature request.

**Comment by takezoux2** [comment]
@maykays 
Why this feature is moved to "We won't build" section?
Are you developing this feature in another project? or is this feature beyond the responsibility of this project?

**Comment by gockle** [comment]
Hi @takezoux2  The current design of instance scheduler solution has some limitations which needs to be addressed, we are currently evaluating a new/alternate design options for the solution, Hence at this point we don't want to include/expand this solution in its current architecture to more services. I would suggest you consider taking a look at [AWS Systems Manager Automation](https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-automation.html)

**Comment by takezoux2** [comment]
Thanks😊 I check AWS System Manager Automation.

**Comment by rostskadat** [comment]
Hello @gockle, @rakshb 

I understand your suggestion about the AWS Systems Manager Automation for this use case.
However the client I'm working is really interested in having the solution support AWS ECS Service, 
as  that would allow them a quick win in term of cost for their current environment.
I therefore submitted the Pull request #407 specifically for this issue.
Please, do no hesitate to comment anything that might allow a prompt merge of this request.

Thanks for the consideration

**Comment by bientavu** [comment]
Hi @rakshb, we are also really interested for this new feature. Do you have an approximate ETA for this prioritized feature ?

**Comment by CrypticCabub** [comment]
ASG Scheduling is now supported in [v3.0.0](https://github.com/aws-solutions/instance-scheduler-on-aws/releases/tag/v3.0.0), which by extension means that you can schedule the ASGs that run your ECS clusters.

**Comment by villelahdenvuo** [comment]
@CrypticCabub Hey, I was looking into setting up org level instance scheduler and I would like to consolidate our ECS Fargate services to use the same schedule as other services, but it does not use ASG, seems like Fargate has its own scaling system?

Should I open a new issue for supporting Fargate services in the instance scheduler solution?

**Comment by CrypticCabub** [comment]
Yes please do open a FR ticket. I am not too familiar with the inner workings of native fargate personally, but it does sound like a service that we could possibly support in the future.
