### ISSUE TITLE
Support Elastic Kubernetes Service (Amazon EKS)

### ISSUE THREAD

**Issue by zhangwenjia0326** [aws-solutions/instance-scheduler-on-aws#169]
Hi, Does instance scheduler have future plan to support scheduling of EKS cluster? Thanks.

**Comment by maykays** [comment]
Support for scheduling EKS cluster is not currently on the roadmap for Instance Scheduler.  However, I will leave this issue open to allow others to comment if they are interested in this feature. Thank you.

**Comment by KenkoGeek** [comment]
+1

**Comment by panneer-subramanian** [comment]
+1

**Comment by jonassteinberg1** [comment]
+1

**Comment by fbellin** [comment]
+1

**Comment by krr1817git** [comment]
+1

**Comment by dnnytn** [comment]
+1

**Comment by andrescollao** [comment]
+1

**Comment by angelalberici** [comment]
Restarting NodeGroups mean they lose the Schedule Tags, if there was a way of re-injecting the Schedule (ideally through UI) when nodes are re-started that will already solve it 

+1

**Comment by dalvarezquiroga** [comment]
+1 and I don't know if also support Autoscaling Groups.

**Comment by hatim-heffoudhi** [comment]
I don't think we can shut down nodes because of ASG / EKS minimum capacity....  but you can schedule to scale in with ASG
otherwiser +1 for this feature

**Comment by grezar** [comment]
+1

**Comment by miroquantox** [comment]
Supporting ASG would be super nice. This could cover ECS and EKS nodes.

**Comment by miroquantox** [comment]
+1

**Comment by jiba21** [comment]
+1

**Comment by aschaber1** [comment]
+1

**Comment by aschaber1** [comment]
> Supporting ASG would be super nice. This could cover ECS and EKS nodes.

There's a PR #407 now, that focusses on ECS. But IMHO doesn't take ASGs into account, hence no dice for EKS. 🎲

**Comment by rakshb** [comment]
Closing this since this feature is not in the immediate roadmap for the solution. Please comment to re-open this thread.

**Comment by kderck** [comment]
Still interested in this issue. Don't think it should be closed.

**Comment by wiwwo** [comment]
+1 on re-opening and keeping it as a reminder of future roadmaps

**Comment by aschaber1** [comment]
We found another solution for this:

We are now using karpenter in consolidation mode, which will consolidate pods onto nodes and shut down unused nodes.
We also use kube-downscaler (alternatives could be: kube-green[3] and keda[4]) to schedule downtimes for certain namespaces.
This combination causes karpenter to consolidate nodes and shut them down during the night, and scale back up when we need them.

[1] https://karpenter.sh/v0.32/concepts/disruption/
[2] https://codeberg.org/hjacobs/kube-downscaler
[3] https://github.com/kube-green/kube-green
[4] https://keda.sh/docs/2.12/scalers/cron/

**Comment by wiwwo** [comment]
@aschaber1 That is cool! Trying it straight away, thanks!
