### ISSUE TITLE
Feature request: Temporary override

### ISSUE THREAD

**Issue by ghost** [aws-solutions/instance-scheduler-on-aws#202]
We're beginning to use this solution to power off non-production instances at night.  Occasionally, one needs to be brought up, off-hours, to facilitate some additional testing or deployment.  It might only need to be on for an hour or two, not all night.  We have a number of options, as I see it:

1. With `enforced=false`, use EC2 API's to power the instance on and then also power off when done.
2. Set `override_status=running`, and then remove the value when the window is done.
3. Add a new period reflecting just the few hours it needs to be up, and then remove the period when done.

All of these options require us, outside of this solution, to do _something_ at the end of the ad-hoc uptime period.

I know your state decision logic already has a lot of factors and probably is getting complicated, but I wonder if you could add one or two new schedule attributes.  Perhaps something like:
`temporary_override_status `= running or stopped
`temporary_override_expiration`=(datetime)
And during evaluation, if the value of `temporary_override_expiration` is in the future, use `temporary_override_status` as if it were a normal `override_status` value.

Just a thought, appreciate any feedback, and the solution itself.

**Comment by gockle** [comment]
@jgardsentry We will take a look at this suggestion and see if we can incorporate this in a future release.

**Comment by rakshb** [comment]
We do not have plans to support this feature in the solution.
