### ISSUE TITLE
How to schedule EC2 instance to turn-off for next 30 days

### ISSUE THREAD

**Issue by skrishna-dhcs** [aws-solutions/instance-scheduler-on-aws#209]
Hi
How to schedule EC2 instance to turn-off for next 30 days, on dynamoDB period and schedule

**Comment by gockle** [comment]
Hi @skrishna-dhcs Can you provide more information regarding this? Like should the instance be started and kept in Started state indefinitely or should the instance be started after 30 days and then scheduled for specific days/hours?
