### ISSUE TITLE
Feature request: Option to Add list of Local Holidays

### ISSUE THREAD

**Issue by Preenesh** [aws-solutions/instance-scheduler-on-aws#231]
An option to add list of Local Holidays apart from just business days

**Comment by maykays** [comment]
Thank you for the suggestion. We have added it to the backlog.

**Comment by chatchai-komrangded** [comment]
+1 This is frequent ask from every customer engagement.

**Comment by anakinnet** [comment]
+1

**Comment by oze10t** [comment]
+1 I got this mention all the time from my customers

**Comment by chatchai-komrangded** [comment]
Any update so far. :)

**Comment by sarah-carrez** [comment]
+1

**Comment by satishpatil040590** [comment]
+1

**Comment by chatchai-komrangded** [comment]
+1 so far.

**Comment by awsnolan** [comment]
+1 for my customers

**Comment by rakshb** [comment]
This feature request has been prioritized in our backlog for a future release.

**Comment by rakshb** [comment]
@Preenesh, @chatchai-komrangded, @satishpatil040590, @anakinnet, @oze10t, @awsnolan  - Would you be willing to talk to us to get more detailed requirements on this feature?
