### ISSUE TITLE
InstanceType Property ignored

### ISSUE THREAD

**Issue by whoDoneItAgain** [aws-solutions/instance-scheduler-on-aws#245]
I deployed this solution earlier this week and have ran into the same problem described in #130 . The workaround @aquexata used resolved this for me as well.

running v1.3.3

**Comment by gockle** [comment]
Hi @whoDoneItAgain This indeed seems to be an issue that was not resolved in the earlier issue [130](https://github.com/awslabs/aws-instance-scheduler/issues/130), I will add it to the backlog for the solution, it will be addressed in a future release, for setting up schedules use the [scheduler-cli](https://docs.aws.amazon.com/solutions/latest/instance-scheduler/appendix-a.html) option which is provided with the solution.

**Comment by hearde** [comment]
Fixed in [v1.5.1](https://github.com/aws-solutions/instance-scheduler-on-aws/releases/tag/v1.5.1)
