### ISSUE TITLE
ignore rds multi-az

### ISSUE THREAD

**Issue by whoDoneItAgain** [aws-solutions/instance-scheduler-on-aws#252]
was getting errors about not able to stop RDS instances. Come to find out, those instances are multi-az so they cant be shutdown. Would be nice if the scheduler recognized that, logged it, and skipped shutting it down instead of erroring out.

Use case for keeping it in the schedule: Environment that, when not in QA for release, is set to single-az and shutdowns down as scheduled. When a release is pending, we switch it to multi-az to as closely as possible replicate our prod environment. Its one less thing to have to manage.

Error I receive:

Error : ERROR   : Error stopping rds instance RDS:dbName (dbName), (Shape is missing required key 'type': OrderedDict([('members', OrderedDict([('SourceRegion', OrderedDict([('shape', 'String'), ('documentation', '<p>The ID of the region that contains the source for the db instance.</p>')]))]))]))

**Comment by gockle** [comment]
@whoDoneItAgain Sorry about the issue, can you confirm if you are using the latest version of instance scheduler v1.4.0, which has the changes to ignore this error (i.e logs the error in cloudwatch but resumes scheduling the rest of the RDS instances with the schedule defined)? If you are already using v1.4.0 and still facing this issue please let us know we will investigate it further.

**Comment by gockle** [comment]
@whoDoneItAgain I tried replicating the issue, I was able to see that the solution was generating the error message in the log files for the db instance within the cluster. But the solution did schedule/stop the rest of the instances, can you let me know how many instances were running the same account/region which were not being stopped and how many instances were hosted in the account/region in total?
