### ISSUE TITLE
Read patch group tag value to determine maintenance window for EC2

### ISSUE THREAD

**Issue by jarridkleinfelter** [aws-solutions/instance-scheduler-on-aws#258]
Add a feature to the AWS instance scheduler so that it reads in the “Patch Group” tag value for each EC2 instance and determines the maintenance window associated with that Patch Group and starts the instance before the maintenance window and stops the instance at the end of the maintenance window. This behavior would be similar to how the AWS instance scheduler handles RDS databases when the option “use_maintenance_window = true” is set for a given schedule as described [here](https://docs.aws.amazon.com/solutions/latest/instance-scheduler/components.html#schedule-definitions). The following section is taken from the [link](https://docs.aws.amazon.com/solutions/latest/instance-scheduler/considerations.html#amazon-rds-maintenance-window) –
 
“Every Amazon RDS instance has a weekly [maintenance](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.Maintenance.html#Concepts.DBMaintenance) window during which any system changes are applied. During the maintenance window, Amazon RDS will automatically start instances that have been stopped for more than seven days to apply maintenance. Note that Amazon RDS will not stop the instance once the maintenance event is complete.
 
The Instance Scheduler allows you to specify whether to add the preferred maintenance window of an Amazon RDS instance as a running period to its schedule. The solution will start the instance at the beginning of the maintenance window and stop the instance at the end of the maintenance window if no other running period specifies that the instance should run, and if the maintenance event is completed.
If the maintenance event is not completed by the end of the maintenance window, the instance will run until the scheduling interval after the maintenance event is completed. For more information about the Amazon RDS maintenance window, refer to [Maintaining a database](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.Maintenance.html) instance in the Amazon RDS User Guide.“
 
With this feature in place we wouldn’t need to explicitly set the “ssm-maintenance-window” field for each schedule. For example, since there are five maintenance windows teams can choose to use, instead of a single schedule such as stop-16:00-mon-sun
there would need to be five schedules created such as stop-16:00-mon-sun-pg1, stop-16:00-mon-sun-pg2, stop-16:00-mon-sun-pg3, stop-16:00-mon-sun-pg4 and stop-16:00-mon-sun-pg5. Same schedule but different maintenance window.

**Comment by gockle** [comment]
Hi @jarridkleinfelter Thanks for the feedback, we will add this to our backlog to be prioritized for a future release of the solution.

**Comment by rakshb** [comment]
We reviewed this request and do not currently have plans to support this feature in the solution.
