### ISSUE TITLE
Can aws-instance-scheduler extended to start and shutdown AppStream 2.0 fleets?

### ISSUE THREAD

**Issue by irshadc** [aws-solutions/instance-scheduler-on-aws#260]
Instance scheduler works best with EC2. We are looking to seek the possibility of extending the same solution with AppStream 2.0 fleet to shut them down during off hours & weekend. Is there a possibility for the same?

**Comment by gockle** [comment]
@irshadc Currently we don't have any plans to support AppStream 2.0 in aws-instance-scheduler. I would suggest looking into using AWS Systems Manager Automation(s).
