### ISSUE TITLE
Integration with SSM Change Calendar

### ISSUE THREAD

**Issue by abjoerne** [aws-solutions/instance-scheduler-on-aws#261]
**Use case:**  As a developer/project manager/system owner I would like to save money by not running instances and databases during holidays and vacation seasons. 

Example:
When the project have vacation or is inactive in a period, we add an event to the calendar for that timeframe 
* Serves and RDS will not be _started_ during that time-frame. 
* Any EC2 and RDS will be stopped if schedule is to stop them. 
* EC2 and RDS will be started/stopped for maintenance-window regardless of calendar-state

**Possible solution:**
Integration with an existing/new change calendar in SSM. The scheduler check the calendar if it is open or closed. This calendar can be used for both local holidays and vacation/project-plan etc 

- Calendar is OPEN: Run scheduler as normal (both starting and stopping)
- Calendar is CLOSED: No starting of instances, only stopping instances if scheduled to do so. 
- Maintenance-windows are always honoured so patching will be performed regardless of calendar-state

**Scope - suggestions one of these:**
(a) Use the named calendar in the defined accounts and regions if present to make it possible by teams to maintain their own calender (add calender-name to cloud-formation)
(b) Use one calendar in the same region/account the main scheduler is running.  (Add ARN to cloudformation)
(c) Use both one "main" calendar (b) and a "regional/accountcalender" (a). Usecase is to use a "Corporate holiday calendar" and also a "Local project calendar"

**Comment by gockle** [comment]
@abjoerne Thanks for the feedback, we will review AWS Systems Manager Change Calendar and add a feature to the solution backlog.

**Comment by rakshb** [comment]
Upon further evaluation, we have decided not to add this feature in the immediate roadmap for the solution.
