### ISSUE TITLE
Feature request: Have the Started and Stopped tags Scheduler message use the default time zone instead of UTC

### ISSUE THREAD

**Issue by JCKrause** [aws-solutions/instance-scheduler-on-aws#263]

**Comment by gockle** [comment]
@JCKrause Thanks for the feedback we will add this feature request to the solution backlog to be prioritized for a future release.

**Comment by rakshb** [comment]
We reviewed this and do not have plans to support this feature in the solution.

**Comment by hearde** [comment]
We could tag instances with the stack default timezone, but in my opinion it doesn't make sense to tag instance that are on a schedule in one timezone with a different timezone. UTC is at least a reasonable default timezone. For example, if the stack default is America/New_York and an instance is tagged with a schedule with a timezone of Asia/Tokyo, it doesn't seem correct to me to tag that instance with a timestamp in the America/New_York timezone.

We could tag instances with the schedule timezone as a default, falling back to the stack default if the schedule does not have a timezone set, but this would result in more calls to tag instances (more time/cost), where currently we only make one call.
