### ISSUE TITLE
Custom Resource Documentation incorrect for CFT field names

### ISSUE THREAD

**Issue by phlrnnr** [aws-solutions/instance-scheduler-on-aws#265]
The [Custom Resource documentation](https://docs.aws.amazon.com/solutions/latest/instance-scheduler/custom-resource.html) states "The custom resource uses the same names and syntax as the fields in the configuration Amazon DynamoDB table."  This is not true.

Based on experimentation and log error messages received via SNS, it appears the valid names/syntax are as follows:

schedule: Description, Enforced, RetainRunning, Metrics, Name, OverrideStatus, Overwrite, Periods, StopNewInstances, Timezone, UseMaintenanceWindow, SsmMaintenanceWindow, NoStackPrefix, Hibernate, ServiceToken, Timeout

period: BeginTime, Description, EndTime, InstanceType, MonthDays, Months, WeekDays

Other field names (such as use_metrics for example) cause the CFT update to fail and roll back.

Can you please update the documentation accordingly?

**Comment by gockle** [comment]
@phlrnnr Thanks for the feedback we will review the documentation and make the updates accordingly.

**Comment by hearde** [comment]
Fixed in [v1.5.1](https://github.com/aws-solutions/instance-scheduler-on-aws/releases/tag/v1.5.1)
