### ISSUE TITLE
some clarification is needed

### ISSUE THREAD

**Issue by ssheff** [aws-solutions/instance-scheduler-on-aws#269]
Do we deploy instance-builder only into the account (kind of OPS account/management account) or it needs to be deployed in every account where we want to control resources? Also, it is unclear how to get output when deploying stacksets (instance-schedule-remote) with all the ARNs that were created in the spoke accounts. Can you please assist? thanks in advance

**Comment by gockle** [comment]
@ssheff You deploy the solution only once in the management account,  in the Cloudformation parameter `cross account roles` you can provide the reference to an AWS Systems Manager Parameter Store in the format `{param:name}`. Once the solutions stack is created successfully. You can deploy the remote template in the secondary accounts and you can update the Parameter Store with the new cross account role create by the remote templates.

**Comment by ssheff** [comment]
excellent and thank you so very much
