### ISSUE TITLE
Terminated Instances appear to break automation

### ISSUE THREAD

**Issue by AleiScho** [aws-solutions/instance-scheduler-on-aws#281]
**Describe the bug**
A terminated ec2 instance stays inside the list of ec2 instances for some time (minutes to hours) with the state "Terminated". When having a terminated instance in that list the automation process seems to fail. I went into the "System Manager > Automation", where the current executions are listed. Executions that were done during the time the terminated instance was listed have failed.

Failure message
Automation Step Execution fails when it is changing the state of each instance. Get Exception from StartInstances API of ec2 Service. Exception Message from StartInstances API: [The instance 'i-abcdefg' is not in a state from which it can be started. (Service: AmazonEC2; Status Code: 400; Error Code: IncorrectInstanceState; Request ID: 7660dda5-ed3d-4992-bc2a-9b87ae4a761c; Proxy: null)]. Please refer to Automation Service Troubleshooting Guide for more diagnosis details.

(I changed the instance ID incase it might be senisitive information. Better save than sorry)

The instance listed by the failure message is the terminated instance. Due to the failure it also does not start the stopped instances. I was only able to get them started with the Scheduler after the terminated instance was gone from my instance list.

I assume that the instance scheduler just takes every instance that does not have the state "running" and tries to change it to running, but thereby it also tries to start the terminated instances as they have the state "terminated" which is not "running" (obviously).

**To Reproduce**
- Create two instances
- Tag both instances
- Terminate one instance
- Try to start/stop the other instance using the instance Scheduler

**Expected behavior**
- The terminated instance should be ignored

**Please complete the following information about the solution:**
- Version: 2.0.0

- Region: eu-central-1
- Was the solution modified from the version published on this repository? unmodified

**Comment by gockle** [comment]
@AleiScho Thanks for the feedback we will look into this.

**Comment by fergoid2511** [comment]
I have seen the same behaviour with terminated instances that are tagged.  The automation fails.
I have also seen issues with instances started with one time spot requests.  They cannot be stopped.
'You can't stop the Spot Instance 'i-zzzzzzzzzzzzzzzzz' because it is associated with a one-time Spot Instance request.'

Is there a way we can configure the automation to continue with other instance ids if one fails >

**Comment by gockle** [comment]
Hi @fergoid2511
* The version 2.0.0 has been rolled back #289 
* The solution is designed to support only on-demand instances.
* The solution (v1.4.0) uses a parameter __START_EC2_BATCH_SIZE__ in the lambda environment variables, the solution attempts to start/stop instances in batches to reduce the number of API calls, If one of the instance in the batch cannot be started or stopped only the instances within that batch will remain in an undesired state. You can update the __START_EC2_BATCH_SIZE__ to 1 and the solution will start/stop instances.

**Comment by hearde** [comment]
Closed since this is an issue with the retracted v2.0.0 release of the solution.

Instance start failures cascading to all other instances in the batch has been fixed in [v1.5.1](https://github.com/aws-solutions/instance-scheduler-on-aws/releases/tag/v1.5.1).
