### ISSUE TITLE
Period Timezones

### ISSUE THREAD

**Issue by whoDoneItAgain** [aws-solutions/instance-scheduler-on-aws#302]
I'd like to see a feature added where you can override the stack/schedule time zone on individual periods.

Similar to how you can override the stack default timezone on a schedule, this would allow us to override the schedule timezone at the period level.

Use Case:

We create the schedule in the time zone that the resource(s) are used (America/New_York primarily). We also utilize AWS Backups. AWS Backups, and many other event services, only follows UTC time. This leads to a situation where we are having to convert the time manually and, this is the bigger issue, we are creating larger ON periods than necessary. Since UTC doesn't follow DST, we have to keep instances on 1 hour longer to accommodate the changing time offset throughout the year. The instances will turn off an hour later in the winter and will turn on an hour early in the summer.

**Comment by dboitnot** [comment]
This could be implemented by adding support for the new EventBridge Scheduler product.

**Comment by rakshb** [comment]
We do not have plans to support this feature in the solution.
