### ISSUE TITLE
Cannot Assume Role with custom-named cross-account roles

### ISSUE THREAD

**Issue by theksi** [aws-solutions/instance-scheduler-on-aws#311]
Hello
I hope that you're doing fine !!
Just to report an issue we've encountered and hopefully fixed when using instance scheduler cross-account
When experimenting cross-account instance scheduler we rapidly encountered the following error

```shell
ERROR   : Can not assume role arn:aws:iam::XXXX:role/OpsmgmtInstanceScheduler for account XXXX, (An error occurred (AccessDenied) when calling the AssumeRole operation: 
User: arn:aws:sts::YYYY:assumed-role/ios-vmmgmt-instance-scheduler-SchedulerRole-1H72SJEAZA4YG/ios-vmmgmt-instance-scheduler-InstanceSchedulerMain 
is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::YYYY:role/OpsmgmtInstanceScheduler))
```
After some investigation we identified that the issue was link to the resource ARN in the Ec2PermissionsB6E87802 in-line policy of the instance-scheduler-SchedulerRole and fixed it

I would recomand to make a few changes in the template so that the cross-account role name is set as a template's parameter and then adapt the following stanzas in the policy :

```json
{
              "Action": "sts:AssumeRole",
              "Effect": "Allow",
              "Resource": {
                "Fn::Sub": "arn:${AWS::Partition}:iam::*:role/*EC2SchedulerCross*"
              }
```
by something like

```json
{
              "Action": "sts:AssumeRole",
              "Effect": "Allow",
              "Resource": {
                "Fn::Sub": "arn:${AWS::Partition}:iam::*:role/${ParamRoleName}"
 }
```

Thank you for this instance scheduler, a real time saver!!

**Comment by deolank** [comment]
Did you create the spoke account role on your own or use the remote template provided by the solution?

**Comment by theksi** [comment]
Not sure what you mean with spoke account
	- The roles on the management account was created using the template
	- The cross-account role was created within our own template as required by our security for cross-account role audit and contains the stanzas in the templates. Name of the role has been standardized to fit to cross-account role names
