### ISSUE TITLE
Instance scheduler state table not filled

### ISSUE THREAD

**Issue by gshetty437** [aws-solutions/instance-scheduler-on-aws#312]
I deployed a new ec2-scheduler, also deployed cross account role, and updated that role in the original CFN parameter.

I added a new schedule and period, but it didn't stop/start my target instance. On checking, I found my state table was not filled.

So does the state table get filled automatically or do I need to update anything manually on it?

**Comment by deolank** [comment]
The state table is updated by the solution based on the instance state.

**Comment by gshetty437** [comment]
thank you for the response, the issue is resolved, i was still using the old IAM role/policy template in my child account, once I updated that, it started working.
