### ISSUE TITLE
Instance Type not reflected in schedule

### ISSUE THREAD

**Issue by whoDoneItAgain** [aws-solutions/instance-scheduler-on-aws#315]
When specifying an instance type, the period referenced in the schedule is not updated with @instancetype. screenshot of cloudwatch log showing the period resource sent to _create_period and the corresponding created schedule output

![image](https://user-images.githubusercontent.com/12127434/171473551-58093523-6346-426b-bb6e-27b6ec148909.png)

Appears to be / tested an easy fix of swapping lines 159 and 160 of the schedule_resource_handler.py resource handler.

Pull Request #314

**Comment by hearde** [comment]
Fixed in [v1.5.1](https://github.com/aws-solutions/instance-scheduler-on-aws/releases/tag/v1.5.1)
