### ISSUE TITLE
Support Autoscaling Groups (Amazon ASG)

### ISSUE THREAD

**Issue by jiba21** [aws-solutions/instance-scheduler-on-aws#317]
Hi,

Does the instance scheduler have future plan to support the scheduling of ASGs?
We would centralize in the same system the scheduler of all systems, like RDS and EC2. 

Thanks

**Comment by devstek** [comment]
+1

**Comment by rakshb** [comment]
This is prioritized for a future release. Closing this since it is a duplicate of #15
