### ISSUE TITLE
Feature Request: Notifications when schedule is not followed

### ISSUE THREAD

**Issue by kenneth-walden** [aws-solutions/instance-scheduler-on-aws#330]
Consider the following scenario:
1) retain_running is set to "true"
2) An instance is manually started outside the scheduled time.

We would like a notification if the scheduler finds an instance manually started at the scheduled start time (something like "instance-x is scheduled to start now, but was manually started and will remain running until manually stopped") and at the scheduled stop time (something like "instance-x is scheduled to stop now, but was manually started and will remain running until manually stopped").

This isn't an error; rather it is an operational alert, so we would configure a SNS topic to route these messages to the business team responsible for the relevant instance.

**Comment by rakshb** [comment]
Thanks for the request. We do not have plans to support this feature in the immediate solution roadmap. Please comment to upvote and re-open this thread.
