### ISSUE TITLE
Instance scheduler is failing to start instance at its scheduled time

### ISSUE THREAD

**Issue by lady-wanderer** [aws-solutions/instance-scheduler-on-aws#332]
Summary:
1. Lambda does not experience errors on days the instance fails to start.
2. On days the instance fails to start, the StartInstances API is never called for the affected EC2 Instance.
3. The Schedule period is correctly constructed, but the Function does not seem to follow the rule set in the function. Most invocations in the month of October are on Monday and Wednesday, with some on Thursday and Friday.

I have a schedule configured from 00:00 est to 21:00 pm est, Monday-Friday. Most days, the solution works and stops and starts instances at the correct time. However, sometimes the solution will not start an instance after it has been stopped. Subsequent runs after the start time, do not trigger the instance to start either.

**Comment by labkey-jony** [comment]
@lady-wanderer Are you on the newest version of the scheduler?

My org's seeing a similar issue where EC2 instances are not starting up in the mornings. However, we're on `1.3.1` and we're hoping bumping to `1.4.1` will remedy this.

**Comment by lady-wanderer** [comment]
This is no longer an issue. I went to version 1.4.1 and it fixed it.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by labkey-jony** [comment]
Confirmed on my end as well. I had to both upgrade to `1.4.1` and also make sure the `KMS:CreateGrant` permission to my scheduler role since we're using encrypted EBS volumes and set my resource for that permission to cover those as well. Something like `"Resource": ["arn:aws:kms:us-west-2:AWS_ACCOUNT_ID:key/*"]`

**Comment by easante817** [comment]
I have added the KMS:CreateGrant but still not working. wondered if I did it wrong

**Comment by jmd-au** [comment]
Can also confirm this is occurring for instances being managed through this solution for me.

````
“errorMessage”: “User: arn:aws:sts::[REDACTED]:assumed-role/[REDACTED/[REDACTED]-instance-scheduler-website-prod-InstanceSchedulerMain is not authorized to perform: kms:CreateGrant on resource: arn:aws:kms:us-west-2:[REDACTED]:key/[REDACTED] because no identity-based policy allows the kms:CreateGrant action”,
````

**Comment by CrypticCabub** [comment]
Hi @jmd-au 

have you tried adding permission to access the KMS key to your scheduler role as described in the implementation guide here?
https://docs.aws.amazon.com/solutions/latest/instance-scheduler-on-aws/plan-your-deployment.html

If so, is there anything that is particularly confusing or unclear?
We are looking to improve the troubleshooting documentation around this particular issue so any extra information on what customers need to be able to understand the solution as easily as possible is much appreciated!

**Comment by jmd-au** [comment]
A colleague came to the same conclusion (needing to add `kms:CreateGrant` to the policy, so added it yesterday and now the scheduler is functioning as expected.

The main thing is that for something that should be done to conform with best practice (encryption at rest), I would suggest that this should be highlighted more than an single line in the documentation.

Another suggestion is that this could _somewhat easily_ be included through a boolean in the CloudFormation template. e.g: Are you using KMS encryption on your EBS volumes for EC2? - which would then conditionally add the statement to the policy.

**Comment by 65156** [comment]
if the ec2 is manually stopped, inside the shutdown policy, it appears that the schedule will require an enforced setting to override.

https://github.com/aws-solutions/instance-scheduler-on-aws/issues/322

**Comment by CrypticCabub** [comment]
[v3.0.0](https://github.com/aws-solutions/instance-scheduler-on-aws/releases/tag/v3.0.0) now includes a CloudFormation parameter to provide the scheduler with CreateGrant permissions to KMS keys
