### ISSUE TITLE
Scheduling for DocumentDB and NeptuneDB instances

### ISSUE THREAD

**Issue by rakshb** [aws-solutions/instance-scheduler-on-aws#336]
Please up-vote if you want this feature.

**Comment by jaemokhong** [comment]
We are considering integrating DocumentDB into our service. The addition of a scheduler for DocumentDB is crucial, especially when factoring in costs during the development phase. Therefore, I would appreciate it if you could provide information on when this feature might be added.

**Comment by CrypticCabub** [comment]
hi @jaemokhong.

Apologies for the delay in getting back to you. This feature has been prioritized for inclusion in our next release, though I am unfortunately not able to provide an estimate as to when exactly that release will go live.

However, under the hood DocumentDB uses all the same APIs as RDS clusters, so while the current 1.5.3 release does not officially support DocumentDB, it should be able to schedule your DocDB clusters using the RDS Cluster scheduling feature without any additional modification (the majority of our changes around this feature so far have been in handling specific edge-cases and supporting it natively in the configuration, the core scheduling logic itself has not needed modification)

**Comment by CrypticCabub** [comment]
Added in [v3.0.0](https://github.com/aws-solutions/instance-scheduler-on-aws/releases/tag/v3.0.0)
