### ISSUE TITLE
Overlapping schedules

### ISSUE THREAD

**Issue by hamza-fareed** [aws-solutions/instance-scheduler-on-aws#338]
Hi, 

I am looking to use the AWS instance scheduler to control start stop as well as instance resize for a server on a specific day of the month. The issue I am facing is that the resize overlaps the general start stop period and the instance keeps stopping and starting and does not resize. 
I have upgraded to 1.4.1 and the issue still persists. Is something like this possible? as I seem to be failing to set it up successfully.
Period : 
`      {
         "Begintime": "17:25",
         "Endtime": "17:45",
         "Description": "Tuesday test hours",
         "Weekdays": [
            "tue"
         ],
         "Name": "svc-02-tue-hours",
         "Type": "period"
      },
      {
         "Begintime": "17:25",
         "Endtime": "17:45",
         "Description": "Availability Zone B operational hours",
         "Weekdays": [
            "mon-sun"
         ],
         "Name": "zoneb-std-hours",
         "Type": "period"
      }` 

Schedule :
`      {
         "UseMaintenanceWindow": false,
         "StopNewInstances": true,
         "UseMetrics": false,
         "Hibernate": false,
         "Enforced": false,
         "RetainRunning": false,
         "Description": "SVC-02 schedules",
         "Periods": [
            "svc-02-tue-hours@t2.small",
            "zoneb-std-hours@t2.micro"
         ],
         "Name": "svc-02-schedule",
         "Type": "schedule"
      }`

**Comment by hearde** [comment]
Overlapping periods with different instance types will cause the scheduler to thrash, because the instance is never the correct type in the overlapping period. You can fix this by changing the "Weekdays" field of the "zoneb-std-hours" period to "mon,wed-sun" so the periods don't overlap.
