### ISSUE TITLE
Feature Request: handle transfer family instances scheduling

### ISSUE THREAD

**Issue by yfengBTI** [aws-solutions/instance-scheduler-on-aws#371]
Feature Request:
Can the instance scheduler support TFR instances as well as EC2 instances?

**Comment by CrypticCabub** [comment]
@yfengBTI Thanks for your feature request!

If anybody else would also like to see this feature, please thumbs-up or comment on this thread so that we can better track it.

**Comment by rakshb** [comment]
We do not have plans to support this feature in the immediate solution roadmap. Please comment to re-open this ticket.
