### ISSUE TITLE
Support for custom prefixes in role names

### ISSUE THREAD

**Issue by jej2003** [aws-solutions/instance-scheduler-on-aws#378]
In some stricter environments it is required to follow certain naming conventions associated with resource creation, specifically roles.  It would be ideal if there was a way to provide a custom prefix to resources like roles such that they can be named according to the required convention.

**Comment by jej2003** [comment]
The environment we deploy into limits of he role names that they must have a specific prefix. There is no option to create roles that do not follow this pattern

**Comment by rakshb** [comment]
We do not have plans to support this feature in the solution.
