### ISSUE TITLE
value of tag schdeule to be ignored  

### ISSUE THREAD

**Issue by MO-BENCHEIKH** [aws-solutions/instance-scheduler-on-aws#416]
Hello,

for governace approach we want put the tag schedule for all instance event scheduled to start and stop or not, for those that are not scheduled  we will put a value ( AlwaysON for exemple ) that not match with any schedule in the instance scheduler stack 
can you please  help us how this value  to be igonred in the stack and not  generate any error or warring message for this value of schedule tag.

Regards,
M.BENCHEIKH

**Comment by CrypticCabub** [comment]
Thanks for the feature request!

We have added this to our backlog to be included in a future release.

**Comment by hearde** [comment]
Duplicate #322
