### ISSUE TITLE
DynamoDB not updating following CloudFormation Update

### ISSUE THREAD

**Issue by neilromatowski0373** [aws-solutions/instance-scheduler-on-aws#481]
Hi,

We use instance scheduling and recently hit a limit on byte size (Change set fails with 'length is greater than 4096') in a CloudFormation parameter (link to issue here - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html). We worked with Support to create a new parameter and a join to allow us to create an extension to CrossAccountRoles. This resolved the issue, or so it appeared. I have recently added a new ARN and processed the update via CloudFormation in the usual manner. There were no errors but upon checking the following day I could see that the resource did not behave as expected (i.e. shut down and start up on schedule). I checked the CloudWatch logs and could not see an entry for the new instance. I then checked the DynamoDB and could not see anything in the State Table. I have re-opened the case with Support who are reaching internally. They pointed me in this direction too. I would expect that the update of the stack (each time we add a new ARN) should create an entry in the Dynamo DB State Table. Is this correct? Looking for help to recover this to a working state and allow us to add more remote accounts. Happy to provide any supporting information required.

Kind Regards.

Neil.

**Comment by CrypticCabub** [comment]
Hi Neil,

How did you extend the CrossAccountRoles parameter? The limitation you described is a known limitation for which Instance Scheduler provides 2 alternative solutions for out of the box

The first option is to use automatic spoke account registration via AWS Organizations.

The second option would be to define your spoke account IDs using SSM parameters and let the solution dynamically load these account ids directly from SSM during scheduling. 

You can find details on both of these approaches in our IG here: 
https://docs.aws.amazon.com/solutions/latest/instance-scheduler-on-aws/cross-account-instance-scheduling.html

I hope that helps!
Cryptic

**Comment by neilromatowski0373** [comment]
Hi Cryptic,

Thank you for reaching back. The following is what I wrote up following my interaction with Support. It seemed to work but maybe is not a viable solution? I have attached my notes as an attachment. Hope that has come through.

Many thanks.

![Screenshot 2023-09-19 205814](https://github.com/aws-solutions/instance-scheduler-on-aws/assets/145494862/82e7bbb3-13d9-4ae8-8ac9-ce4481d1b16a)

**Comment by CrypticCabub** [comment]
You can use that method if you would like to manually edit the cloud formation template. However what Support could not have known is that Instance Scheduler already provides a built-in way to handle this scenario without needing to modify the template (quite helpful when updating to new versions).

If you are on the latest version (1.5.1), the preferred approach would be to use automatic registration with AWS Organizations. If that doesn't work for you, I would recommend using the SSM Parameters approach as it will allow you to add additional accounts to the ssm parameter without having to issue an extra CloudFormation update

**Comment by neilromatowski0373** [comment]
Hi Cryptic,

So I have upgraded our hub and spoke to 1.5.1. I have elected to use the account ID in the parameter and all appears to be working :). Is there a way to calculate the quota used in the actual parameter field. We have over 300 accounts and we have not long started pushing this out. I don't think we would hit the same issue (4096) but it would be handy to be able to monitor this. Thank you for your support and pointers with this. I am going to close the case.

**Comment by CrypticCabub** [comment]
in terms of the number of characters being used in the CloudFormation? I am not aware of a convenient way of monitoring that specifically, but I will note that the SSM Parameter support provided by Instance Scheduler allows you to define multiple accounts per SSM parameter (as a comma-separated list) and you can then provide multiple SSM parameters to the CloudFormation input field. Together this means that the theoretical upper limit should be far beyond real-world use cases
