### ISSUE TITLE
Latest version of CloudFormation template is not deployed in official s3 bucket

### ISSUE THREAD

**Issue by natten426** [aws-solutions/instance-scheduler-on-aws#482]
**Describe the bug**

The latest version of CloudFormation template in the s3 bucket "solutions-reference" is "v1.5.0".

**To Reproduce**

```zsh
$ curl -s https://s3.amazonaws.com/solutions-reference/aws-instance-scheduler/latest/aws-instance-scheduler.template | grep version
 "Description": "(SO0030) - The AWS CloudFormation template for deployment of the aws-instance-scheduler, version: 1.5.0",
      "default": "Scheduler (version 1.5.0)"
     "version": {
    "Description": "EC2 and RDS instance scheduler, version 1.5.0",
    "Description": "Instance Scheduler - Rule to trigger instance for scheduler function version 1.5.0",
    "stack_version": "1.5.0",
```

**Expected behavior**

"v1.5.1" template is retrieved.

- [x] Version: v1.5.1

**Comment by CrypticCabub** [comment]
with the latest release of Instance Scheduler (1.5.1), the internal paths have been updated to match the name of the solution. The correct path for the latest release of Instance Scheduler would now be:

https://solutions-reference.s3.amazonaws.com/instance-scheduler-on-aws/latest/instance-scheduler-on-aws.template
