### ISSUE TITLE
CLI Documentation: --use-metrics not a valid option

### ISSUE THREAD

**Issue by MichaelDavisTSN** [aws-solutions/instance-scheduler-on-aws#489]
**Describe the bug**

The documentation for scheduler-cli lists --use-metrics as an option (with a required true or false argument), but an update-schedule command returns the error "scheduler-cli: error: unrecognized arguments: --use-metrics true"

**To Reproduce**

Run a create or update command specifying the --use-metrics option (with either a true or false argument)

**Expected behavior**

No error will be produced, and a subsequent describe-schedules command displays the value of the UseMetrics parameter.

**Please complete the following information about the solution:**

- [ ] Version: [e.g. v1.0.0]

(SO0030) instance-scheduler-on-aws v1.5.1
scheduler-cli 2.2.2.0

- [ ] Region: [e.g. us-east-1]

us-east-1

- [ ] Was the solution modified from the version published on this repository?

no

- [ ] If the answer to the previous question was yes, are the changes available on GitHub?

n/a

- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for
      the sevices this solution uses?

n/a

- [ ] Were there any errors in the CloudWatch Logs?
      [Troubleshooting](https://docs.aws.amazon.com/solutions/latest/instance-scheduler-on-aws/troubleshooting.html)

It looks like the command is not going through and is failing locally, as there are no entries in the CloudWatch logs indicating that the --use-metrics option was used.

**Screenshots**

[root@<redacted> ]# scheduler-cli update-schedule --periods alldays-0800-1700 --name alldays-0800-1700 --use-metrics true --retain-running false --stop-new-instances true --enforced false --description "Starts at 0800 and stops at 1700 every day" --stack amazon-instance-scheduler
usage: scheduler-cli [-h] [--version]
                     {create-period,create-schedule,delete-period,delete-schedule,describe-periods,describe-schedule-usage,describe-schedules,update-period,update-schedule} ...
scheduler-cli: error: unrecognized arguments: --use-metrics true

**Additional context**

**Comment by CrypticCabub** [comment]
Hi @MichaelDavisTSN 

Thanks for opening this issue! 

The cli treats the presence of the --use-metrics flag as indicating that the value should be "true" and the absence of that flag as a value of "false" (same for all other boolean flags) so in your example you would write:

```scheduler-cli update-schedule --periods alldays-0800-1700 --name alldays-0800-1700 --use-metrics --stop-new-instances --description "Starts at 0800 and stops at 1700 every day" --stack amazon-instance-scheduler```

(omit boolean values that you want to be false, and include ones that you want to be true)

I have added a task to our backlog to address this discrepancy in an upcoming release.

**Comment by hearde** [comment]
This has been addressed [in our documentation](https://docs.aws.amazon.com/solutions/latest/instance-scheduler-on-aws/available-commands.html#create-schedule).
