### ISSUE TITLE
DynamoDB enable deletion protection for tables

### ISSUE THREAD

**Issue by tfentonz** [aws-solutions/instance-scheduler-on-aws#502]
**Is your feature request related to a problem? Please describe.**

The AWS Security Hub AWS Foundational Security Best Practices control [[DynamoDB.6] DynamoDB tables should have deletion protection enabled](https://docs.aws.amazon.com/securityhub/latest/userguide/dynamodb-controls.html#dynamodb-6) reports failing checks for the instance scheduler DynamoDB tables:
* ConfigTable
* StateTable
* MaintenanceWindowTable

> You can protect a DynamoDB table from accidental deletion with the deletion protection property. Enabling this property for tables helps ensure that tables don't get accidentally deleted during regular table management operations by your administrators. This helps prevent disruption to your normal business operations.

**Describe the feature you'd like**

Enable deletion protection for the 3 tables.

Add `deletionProtection: true,` property.

**Additional context**

Announcement on Mar 8, 2023 [Amazon DynamoDB now supports table deletion protection](https://aws.amazon.com/about-aws/whats-new/2023/03/amazon-dynamodb-table-deletion-protection/).

AWS CDK API Reference

* aws_dynamodb class Table (construct) [deletionProtection?](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_dynamodb.Table.html#deletionprotection)

**Comment by CrypticCabub** [comment]
Hi @tfentonz

Thanks for submitting this FR, I have added it to our backlog for consideration in an upcoming release

**Comment by CrypticCabub** [comment]
Fixed in [v3.0.0](https://github.com/aws-solutions/instance-scheduler-on-aws/releases/tag/v3.0.0)
