### ISSUE TITLE
Support for Israel(Tel Aviv) Region "il-central-1"

### ISSUE THREAD

**Issue by veltz-avi** [aws-solutions/instance-scheduler-on-aws#503]
**Describe the bug**

When I run the solution deployment in **il-central-1** region (Tel Aviv) I get the following error

`Resource handler returned message: "Error occurred while GetObject. S3 Error Code: IllegalLocationConstraintException. S3 Error Message: The unspecified location constraint is incompatible for the region specific endpoint this request was sent to. (Service: Lambda, Status Code: 400, Request ID: 38f42ebe-4909-4eba-9f12-61706bf9af09)" (RequestToken: 6bfd0154-9ebb-f698-a60b-594cf9f52c3f, HandlerErrorCode: InvalidRequest)`

**To Reproduce**
Deploy the solution in  **il-central-1** region (Tel Aviv)

**Please complete the following information about the solution:**

- [ ] Version: [1.5.3] - 2023-10-22
- [ ] Region: il-central-1

![Screenshot 2023-12-18 at 21 48 04](https://github.com/aws-solutions/instance-scheduler-on-aws/assets/68636084/f8e45f4b-fc1a-4636-abff-92154c50f540)

**Comment by hearde** [comment]
Solutions do not support the il-central-1 region. You can work around this by uploading the assets to your own bucket, setting up appropriate access, and modifying the bucket path for the Lambda asset in the template to point to your uploaded assets.

**Comment by veltz-avi** [comment]
Thank you. Is there an ETA for il-central-1 region support?

**Comment by hearde** [comment]
Not at this time.

**Comment by CrypticCabub** [comment]
il-central-1 is now supported
