### ISSUE TITLE
Logger does not show any thing

### ISSUE THREAD

**Issue by TranVanDung-Leo** [aws-solutions/instance-scheduler-on-aws#509]
**Describe the bug**
No application log is shown for logger.{info, error, debug,...}

**Expected behavior**
It should show log as the same as print does

- [x] Version: v1.5.3
- [x] Region: us-est-1
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for
      the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?
      [Troubleshooting](https://docs.aws.amazon.com/solutions/latest/instance-scheduler-on-aws/troubleshooting.html)

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by CrypticCabub** [comment]
Instance Scheduler's scheduling logs are sent to a dedicated log group separate from the normal scheduling logs. Additional information on these log files and what they contain can be found here: https://docs.aws.amazon.com/solutions/latest/instance-scheduler-on-aws/log-files.html
