### ISSUE TITLE
'Hibernate' flag doesn't work as documented

### ISSUE THREAD

**Issue by trrbentley** [aws-solutions/instance-scheduler-on-aws#510]
**Describe the bug**

Setting 'Hibernate' to 'True' does not default to stopping the instance if Hibernation is not supported. According to the documentation located [here](https://docs.aws.amazon.com/solutions/latest/instance-scheduler-on-aws/schedules.html):

"If you set the solution to use hibernation, but your instances are not [configured for hibernation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enabling-hibernation.html) or they do not meet the [hibernation prerequisites](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/hibernating-prerequisites.html) , the solution logs a warning and the instances are stopped without hibernation. For more information, refer to [Hibernate your On-Demand Instance or Spot Instance](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Hibernate.html) in the Amazon EC2 User Guide."

The solution does not log a warning, it logs an error and does not shut down the instance. As per cloudwatch log:

ERROR   : Failed to stop EC2 instance with ID i-XXXX: An error occurred (UnsupportedHibernationConfiguration) when calling the StopInstances operation: The instance can't be hibernated because it was not configured at launch for hibernation: i-XXXX

**To Reproduce**

1. Set hibernate to 'True' in schedule against ec2 instances not set to hibernation/or not supported
2. Wait for polling interval
3. Check CW log for error

**Expected behavior**

Scheduler should log a warning about hibernation not supported and STOP the instance.

**Please complete the following information about the solution:**

- [ ] Version: 1.5.3

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example,
_"(SO0030) instance-scheduler-on-aws v1.5.1"_. You can also find the version from
[releases](https://github.com/aws-solutions/instance-scheduler-on-aws/releases)

- [ ] Region: us-east-1
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for
      the sevices this solution uses? Yes
- [ ] Were there any errors in the CloudWatch Logs? Yes (explained above)
      [Troubleshooting](https://docs.aws.amazon.com/solutions/latest/instance-scheduler-on-aws/troubleshooting.html)

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by hearde** [comment]
Thank you for raising this bug. This is a regression in v1.5.1. We will fix this in an upcoming release. To work around this issue, you can downgrade to v1.5.0, or only associate instances that support hibernation to a schedule that specifies hibernation.

**Comment by CrypticCabub** [comment]
Fixed in [v3.0.0](https://github.com/aws-solutions/instance-scheduler-on-aws/releases/tag/v3.0.0)
