### ISSUE TITLE
maximum accounts

### ISSUE THREAD

**Issue by MO-BENCHEIKH** [aws-solutions/instance-scheduler-on-aws#526]
Hello,

Based on your feedback, how many accounts can be supported by a single Lambda with the maximum settings (memory, timeout, etc.) ?

Regards,
M.B

**Comment by CrypticCabub** [comment]
Each account is processed in parallel so there is no known maximum limit for number of accounts Instance Scheduler can support. The only theoretical limit is the lambda concurrency quota configured on your account causing sufficient lambda throttling that we do not complete a scheduling execution within scheduling interval configured on the hub stack, but we're talking well over 1000 targets at this point (1 target = 1 unique combination of account/region/service)
