### ISSUE TITLE
ASG support 

### ISSUE THREAD

**Issue by MO-BENCHEIKH** [aws-solutions/instance-scheduler-on-aws#527]
Hello,

Have you any information that ASG will be supported in scheduling operations in the next release ?

Regards,
M.B

**Comment by CrypticCabub** [comment]
ASG support is currently in active development and has been prioritzed for inclusion in our next release

**Comment by CrypticCabub** [comment]
unfortunately no ETA yet but we will update the ticket once we have a better idea
