### ISSUE TITLE
override_status - replacement

### ISSUE THREAD

**Issue by whoDoneItAgain** [aws-solutions/instance-scheduler-on-aws#535]
**Describe the bug**

not a bug per se. With the deprecation of override_status, what is the recommended replacement?

Our use case for override_status:

When an EC2 that is typically off is needed, the dev team manually turns on the server. If the server is not turned off by the dev team, the override_status=stopped will turn the server off according to the schedule but not turn it back on. Effectively its used to turn servers off at a set time and keep them off until they are manually started again.

**To Reproduce**

n/a

**Expected behavior**

n/a

**Please complete the following information about the solution:**

- [x] Version: 1.4.1

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example,
_"(SO0030) instance-scheduler-on-aws v1.5.1"_. You can also find the version from
[releases](https://github.com/aws-solutions/instance-scheduler-on-aws/releases)

- [x] Region: us-east-1
- [x] Was the solution modified from the version published on this repository? yes
- [x] If the answer to the previous question was yes, are the changes available on GitHub? no
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html)  the sevices this solution uses? n/a
- [x] Were there any errors in the CloudWatch Logs? n/a
      [Troubleshooting](https://docs.aws.amazon.com/solutions/latest/instance-scheduler-on-aws/troubleshooting.html) 

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by whoDoneItAgain** [comment]
hmmm, i'll have to reach back out to the team for clarification. regardless, i'll test the 1-sided stop schedule you mentioned. sounds like that's what i should be using for this use case.

**Comment by whoDoneItAgain** [comment]
we converted to the method described and is working as it should. we are not going to bother investigating the override_status behavior since its deprecated.

**Comment by CrypticCabub** [comment]
sounds good, glad the schedule is working for you!
