### ISSUE TITLE
Is there a way to have Instance Scheduler support a cron-like syntax to build dynamic schedules in the future

### ISSUE THREAD

**Issue by exolain** [aws-solutions/instance-scheduler-on-aws#536]
We have a really big organization and there are customers who have specific requirements on their schedules. We can have people from Bulgaria/India and London working on the same application and sometimes there schedule might overlap. And a specific set schedule for office hour of a specific region wouldn't be ideal for them

is possible to have an option to use a custom schedule if the time needed is not covered by the ones you are already providing? Perhaps based in a Cron-like syntax.
I understand that the way that the Instance Scheduler is designed right now this might be challenging. But wondering if it can be reviewed as a potential feature in the future. 
Please do let me know if you think it might be impossible to implement on the near future.

The idea would be that the customer would provide a tag with the specific cron syntax to stop and start their instances.
Similar to something like:
InstanceSchedulerStart: "0 5 * * *" 
 * this would run every day at 5am every day

InstanceSchedulerStop: "0 17 * * *"
 * this would run every day at 5pm.

Let me know if you have any questions.

**Comment by CrypticCabub** [comment]
Thanks for reaching out!

Can you help me understand your use-case a little better? I want to make sure we understand the root problem before attempting to engineer a solution. A few questions that come to mind:

- Is there an organizational reason why another schedule cannot be configured in the hub account for these specific use cases (there's no limit on the number of schedules that can be configured)? 
- In what ways would supporting schedule definitions on tags themselves provide a better customization experience for sub-orgs? 
- Would deploying a separate copy of instance scheduler for each department with special scheduling needs address this problem?

**Comment by exolain** [comment]
Hi @CrypticCabub ,

Thanks a lot for the quick response.

Please see responses below in order:

* So basically management doesn't want to open this outlet to the users since our organization already has more than 1000 accounts with different teams with different support models. So, the amount of custom schedules we would need to update on the Cloudformation template could get way to big by all the different requests we might get (some teams wanting a 10-hour schedule, others with a 12-hour schedule with different start / end times). So, this could get us to hit the limit on the CFT template actually, as well as adding an additional operational workload to our team.
*  Previous statement explains a bit for this question as well. Basically would be to allow them better flexibility without having to make code changes 
* Yes, we could also ask them to deploy their own InstanceScheduler instance on their accounts. Let me review with one of the customers who was requesting this feature.

Thanks again!

**Comment by exolain** [comment]
Hi @CrypticCabub ,

one more question. Before asking the customers with going with the option to deploy it on their environment. When I first deployed Instance Scheduler the CLI didn't exist so, I haven't had the chance to use it.
https://docs.aws.amazon.com/solutions/latest/instance-scheduler-on-aws/available-commands.html#create-period

If use the Create Period from the CLI what would that do? would that create the period on the DynamoDB configuration? If the Cloudformation template were to be update it do you know if that would "override" or for some reason remove the period created via the CLI?

**Comment by CrypticCabub** [comment]
Spoke with the team about it and took a closer look at the exact behavior when the CLI and CFN Schedules interact. Currently the CLI does not respect CFN-managed schedules, but I am working on adding that behavior in this week as a late addition to our next major release. No formal release date yet, but we're hoping to be able to go live in the next few months.

**Comment by exolain** [comment]
That's great! Thank you so much ! 🎉 
Will keep an eye on the release notes

**Comment by lorengordon** [comment]
For very similar reasons, I would much prefer for the schedule to be derived from tags on the resources, rather than centrally managed. The team managing the instance scheduler solution is not the same team managing the resources in all the aws accoutns, across the entire organization. It introduces a lot of friction across the teams, trying to support every teams' schedule requirements. If the schedule were simply part of the tag-interface, it would eliminate all the friction. Users could create/set their own schedules, but the solution could be hosted centrally.

**Comment by exolain** [comment]
Hi @CrypticCabub just wanted to let you know we successfully created a Service Catalog product to create schedules for our BU members. The lambda function has the scheduler CLI binary which would take care of creating them

<img width="777" alt="Screenshot 2024-11-07 at 9 34 47 AM" src="https://github.com/user-attachments/assets/20a6929b-d1fe-4dbc-9422-d8be85e1d96e">


<img width="761" alt="Screenshot 2024-11-07 at 9 34 52 AM" src="https://github.com/user-attachments/assets/02307f8f-e1cb-4d18-ab63-63c903434643">

Thanks for your help.

**Comment by exolain** [comment]
Hi Cryptic, 
We can have a call if you would like. I'll send you a message to your mailbox.
I'll start with the second question. We use the Control Tower CFCT customizations pipeline to deploy the Service Catalog Hub & spoke products. And there is a specific Federated role that the SRE users use to login to the accounts within our organization. As part of the Service Catalog product spoke resource we go ahead and associate it to said role so that the SREs will then have access to trigger it. There is also a role that is tied to a couple of Global CI/CD tools that are managed in my company

As for the second question it is a custom resource within the Service Catalog that calls a lambda function that lives in our Shared Services Account. That Lambda function has the layer with the scheduler cli and we access the specific path to run a subprocess to create the schedules from said lambda function.

Hopefully that helps.
