### ISSUE TITLE
Organisation mode and exclude account 

### ISSUE THREAD

**Issue by rootops** [aws-solutions/instance-scheduler-on-aws#537]
Hello,

To simplify the deployment and not be confronted with the character string limitation in  Remote Account IDs, I would like to use the  Organization ID in the deployment and at the same time exclude some accounts, do you have an idea how to do this?

Thank you :)
Regards,
MB

**Comment by CrypticCabub** [comment]
What do you mean by excluding accounts? If you use the organizition-id approach, any spoke stacks deployed to the same organization will be automatically registered with the hub account, but accounts that have not had the spoke stack deployed to them will not be scheduled.

**Comment by CrypticCabub** [comment]
no problem. So was the spoke stack requirement for registration sufficient to cover your use case?

If so, I'll go ahead and close this issue. Please re-open if you have any further questions.
