### ISSUE TITLE
Namespace is required for spoke deployments

### ISSUE THREAD

**Issue by Kevinwochan** [aws-solutions/instance-scheduler-on-aws#548]
**Describe the bug**

![image](https://github.com/aws-solutions/instance-scheduler-on-aws/assets/18486383/025497cb-59cd-47fe-afa0-64464b6cbb60)

**To Reproduce**

Deploy the remote stack without a namespace defined

**Expected behavior**

Documentation says namespaces are optional, either documentation needs to be updated or the SSM parameter needs to be conditionally deployed

**Please complete the following information about the solution:**

- [ ] Version: 1.5.6

**Comment by CrypticCabub** [comment]
Hi Kevin,

Yes, namespace is required to be non-empty. The documentation is incorrect and we are in the process of updating it
