### ISSUE TITLE
link to ASG support documentation 

### ISSUE THREAD

**Issue by MO-BENCHEIKH** [aws-solutions/instance-scheduler-on-aws#556]
Hello,

The link of the implementation guide return to guide of v1.5.4 version, can you give me the right link  for the 3.0.0 version

Regards
MB

**Comment by CrypticCabub** [comment]
If you could send me the link you're referring to I can take a look at getting that fixed.

The latest Implementation Guide for the solution shuld be available from the solution landing page:
https://aws.amazon.com/solutions/implementations/instance-scheduler-on-aws/

direct link to IG: https://docs.aws.amazon.com/solutions/latest/instance-scheduler-on-aws/solution-overview.html

**Comment by CrypticCabub** [comment]
closing as stale
