### ISSUE TITLE
Support for deploying remote roles with stacksets

### ISSUE THREAD

**Issue by hopkinsnji** [aws-solutions/instance-scheduler-on-aws#561]
**Describe the bug**
Instance scheduler currently does not play nicely with cloudformation stacksets. The hub template always deploys a named role, which would be the same name as the named role in the spoke templates. If you deploy the spoke templates with stacksets to an OU that includes the hub account, you won't be able to deploy the hub stack because the Namespace-SchedulerRole already exists in the remote stack. Conversely, if you deploy the hub stack first, then the remote stack(from the stackset) will fail to deploy in the hub account.

**To Reproduce**

Depoly remote stack with a stackset to an OU that includes the hub account. Then deploy the hub stack, and it will fail because it tries to create a role tha already exists in the remote stack.

**Expected behavior**

I expect to be able to deploy the remote stack and the hub stack in the same account as was previously possible.

**Please complete the following information about the solution:**

- [ ] Version: [e.g. v3.0.0]

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example,
_"(SO0030) instance-scheduler-on-aws v1.5.1"_. You can also find the version from
[releases](https://github.com/aws-solutions/instance-scheduler-on-aws/releases)

- [ ] Region: all
- [ ] Was the solution modified from the version published on this repository? NO
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for
      the sevices this solution uses? YES
- [ ] Were there any errors in the CloudWatch Logs? NO
      [Troubleshooting](https://docs.aws.amazon.com/solutions/latest/instance-scheduler-on-aws/troubleshooting.html)

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).
![image](https://github.com/aws-solutions/instance-scheduler-on-aws/assets/45208412/4c5ac109-8937-4225-9b4a-032a5aba8e08)

**Additional context**

**Comment by CrypticCabub** [comment]
To deploy spokes via stackset while ignoring the account where the hub stack is installed, you can use the `AccountFilterType=Difference` flag as described on the stack-set documentation here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/account-level-targets.html

By providing the OU as a target and the Hub account as an account target, the difference flag will then instruct stacksets to filter out the specified accounts from the list of accounts that it will deploy the spoke to.

I hope that helps!

**Comment by tivanov-qb** [comment]
I do not use AWS Organizations parameter, but also using StackSets to deploy the solution. With the latest version (migrating from v1.5.5 to v3.0.2), IAM roles are being created with the same name. This means if you have different regions that you want to cover within the same account, stackset will fail after first region is completed because the IAM role is global and it already exists.

**Comment by CrypticCabub** [comment]
You do not need to deploy multiple copies of the spoke stack for each region of instance scheduler. To enable scheduling for ALL regions in a spoke account, you only need to deploy 1 copy of the spoke stack IN THE SAME REGION as the Hub stack. The IAM Role deployed has sufficient permissions to allow Instance Scheduler to perform cross-region scheduling

**Comment by tivanov-qb** [comment]
hi @CrypticCabub 
thank you for your switft response!

I've previous deployed the solution was with StackSet that was looping over my supported regions. So each region in destination account has it's dedicated stack if you will.
With the newer versions released, does it mean I need to have hub stack per region ? so if i have 4 regions, i need to deploy 4 hub stacks ?

**Comment by CrypticCabub** [comment]
do you have some business requirement for needing a different installation for each region?

The design of Instance Scheduler is specifically geared to allow you to install exactly 1 hub account in a single account/region, and then a single copy of the spoke stack in each member account. Once that is done, Instance Scheduler can schedule all linked accounts, and all regions in those accounts from a single central location (this being one of the main value propositions of the solution)

**Comment by tivanov-qb** [comment]
no, not really business requirement, but as I mentioned version that I used was 1.5.5 and correct if i'm wrong, but few months ago this functionality was not available (sorry if I've missed that)

probably the easiest way to follow the approach you recommend is to delete all present stacks and follow:
https://docs.aws.amazon.com/solutions/latest/instance-scheduler-on-aws/aws-cloudformation-templates.html

**Comment by CrypticCabub** [comment]
Yes, your understanding of 1.5.5's behavior is incorrect. This deployment method has been the consistent design for the lifetime of the solution.

the largest change to the deployment method came in 1.5.0 which added the "Namespace" property to both the hub and spoke stacks. This property made it explicitly possible to install multiple copies of instance scheduler in the same account (and even the same region) so long as they had different namespaces. This was not the primary technical reason for implementing namespaces in the solution, but it is a notable side-effect of the design.

3.0.0 then updated the backend permissions with stricter trust relationships between solution components. These relationships were designed to function within the confines of expected deployment invariants which would explain why you began seeing issues when updated from 1.5.5. For reference, these are the deployment invarients we expect:
- hub account with hub stack installed (no spoke stacks)
- N spoke accounts with 1 spoke stack installed in each
- all stacks (hub and spoke) installed in the same region as one another
- all stacks use the same namespace
- the hub stack is installed before the spoke stacks are deployed
- if opt-in regions are used, they are enabled in both the hub and spoke accounts* 
 
_*more of an edge-case that may not be necessary in all circumstances, your mileage may vary_

**Comment by tivanov-qb** [comment]
@CrypticCabub thanks a lot! I've migrated the solution to hub/spoke setup, everything looks good!
