### ISSUE TITLE
Instance Scheduler Hub Multi-Region

### ISSUE THREAD

**Issue by LaurentiuDaniel94** [aws-solutions/instance-scheduler-on-aws#566]
**Is your feature request related to a problem? Please describe.**
So I have multiple AWS accounts that each and one of them is spanning multiple regions. I have a central Account where I intend to deploy the Instance Scheduler Hub. From the docs I'm not quite sure if I have to deploy the Instance Scheduler Hub 3 times (in all three regions I use) or one is enough. I tried to deploy it in 3 separate regions but it fails because it tries to create the same rolues multiple times and that's not possible because roles are account wide

My question is if I can manage the start/stop of instances from different accounts/regions if I only deploy the Instance-SchedulerHub in one management account in only one region.

**Describe the feature you'd like**

**Additional context**

**Comment by CrypticCabub** [comment]
you only need to deploy the hub once. It can then schedule cross-account and cross-region. The only caveat to be aware of is that all regions you wish to schedule in spoke accounts need to also be enabled in the hub account (even if nothing is installed in those regions) to ensure that the necessary authentication APIs are available for the scheduler to use.
