### ISSUE TITLE
Instance Scheduler not working for Auto Scaling Group

### ISSUE THREAD

**Issue by mozzt** [aws-solutions/instance-scheduler-on-aws#569]
Version: 3.0.3
Region: ap-southeast-2
Was the solution modified from the version published on this repository? no, only memory size of ASGHandler Lambda was increased to test
Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for
the services this solution uses? yes, I am running it in a test environment.
Were there any errors in the CloudWatch Logs? no

I am running Instance Scheduler 3.0.3. It is working for EC2 and RDS but not for Auto Scaling Group. I dont see any error in the cloudwatch logs. I have tried increasing the lambda memory to 256 but it didn't help. 

It created the log groups for EC2 "Scheduler-ec2-xxxx" and RDS "Scheduler-rds-xxxx" but not for ASG. This is a test environment and we have only 1 ASG running. Can you please advise?

**Comment by CrypticCabub** [comment]
I take it you were able to solve your issue?

For anybody else who sees this, documentation on how the ASG feature works can be found here: https://docs.aws.amazon.com/solutions/latest/instance-scheduler-on-aws/advanced-features.html

I will also note tha ASG schedulin operates independently from the EC2 and RDS Scheduling logic and has a separate log-stream attached directly to the `ASGHandler` lambda which you can view for any errors related to ASG scheduling

**Comment by mozzt** [comment]
Thanks for your reply.  My value of the  "Schedule" tag is "stopped" .
Instance Scheduler added the "scheduled" tag to my asg and set the value "scheduled
	
{"schedule": "stopped", "ttl": "2024-09-15T14:48:02.764444+00:00", "min_size": 1, "max_size": 3, "desired_size": 1}

It is not changing the my ASG instances 0-0-0.

**Comment by CrypticCabub** [comment]
what is the configuration of the stopped schedule in your dynamodb table? what you describe implies that instance scheduler has setup the ASG to match the "stopped" schedule to the best of its abilities, but how is that schedule actually implemented?

**Comment by mozzt** [comment]
The attributes of the "stopped" schedule are"
type: schedule
name: stopped
description: Instances stopped
override_status: stopped

**Comment by CrypticCabub** [comment]
the override_status flag is not supported for ASG scheduling as it is impossible to translate the concept to scheduled scaling rules. The first iteration of ASG scheduling is designed to support simple schedules (generally 1 or 2 non-overlapping periods) and weekday/monthday/month fields

**Comment by mozzt** [comment]
It is still not working after changing to "uk-office-hours"

Attributes of uk-office-hour
period: office-hours
timezone: Europe/London

Attributes of period office-hours:
begintime: 09:00
endtime: 17:00
weekdays: mon-fri

the scheduled tag value: {"schedule": "uk-office-hours", "ttl": "2024-09-15T16:48:02.636170+00:00", "min_size": 1, "max_size": 3, "desired_size": 1}

{
    "level": "INFO",
    "location": "_reconfigure_scheduled_actions_to_match_schedule:423",
    "message": "Configuring group test-asg-MyAutoScalingGroup-QM08t76aCz79 with schedule uk-office-hours. Using 1-1-3 as running state",
    "timestamp": "2024-08-16T16:48:02.455+00:00",
    "service": "asg",
    "cold_start": true,
    "function_name": "instance-schedule-303-ASGHandler0F6D6751-uADbejgXNHD3",
    "function_memory_size": "256",
    "function_arn": "arn:aws:lambda:ap-southeast-2:111111111111:function:instance-schedule-303-ASGHandler0F6D6751-uADbejgXNHD3",
    "function_request_id": "147804b4-e819-4878-a86a-ba5132bc1bcd",
    "correlation_id": "826b0b88-51d4-4079-8751-01005ebdcdb2",
    "xray_trace_id": "1-66bf82bd-0489808c5a26f417617aa9f0"
}

	
{
    "level": "INFO",
    "location": "schedule_auto_scaling_group:287",
    "message": "Skipping group test-asg-MyAutoScalingGroup-QM08t76aCz79 with schedule uk-office-hours: All conditions met, current config valid for schedule uk-office-hours until 2024-09-15T16:48:02.636170+00:00",
    "timestamp": "2024-08-16T20:48:00.353+00:00",
    "service": "asg",
    "cold_start": true,
    "function_name": "instance-schedule-303-ASGHandler0F6D6751-uADbejgXNHD3",
    "function_memory_size": "1024",
    "function_arn": "arn:aws:lambda:ap-southeast-2:111111111111:function:instance-schedule-303-ASGHandler0F6D6751-uADbejgXNHD3",
    "function_request_id": "72caeaa4-5268-4b97-9dc1-7d826eca408b",
    "correlation_id": "4ca6962b-904e-418e-aec9-de1c886b38ac",
    "xray_trace_id": "1-66bfbafd-3354b8486354b9c340c40493"
}

**Comment by CrypticCabub** [comment]
I would recommend checking the scheduled scaling rules on your ASG to confirm whether the rules have been setup correctly. 

ASG scheduling functions a little differently compared to EC2/RDS scheduling in that it only interacts with the instance through the scheduled scaling rules (it does this to ensure it plays nicely with any other auto-scaling rules you may have setup). As such, even though these rules might be configured right away, you wont see any change in the ASG instance state until the time comes for one of the rules to kick in

**Comment by mozzt** [comment]
It has set the schedule rule starting "2024 August 20, 02:00:00 AM +10:00". (0-0-0) . thanks for your help.
