### ISSUE TITLE
Lambda Function CreateLogStream Fails with ResourceAlreadyExistsException, Causing Infinite Trigger Loop in Instance Scheduler v3.0.0

### ISSUE THREAD

**Issue by sampreethamithkumar** [aws-solutions/instance-scheduler-on-aws#570]
**Describe the bug**

A Lambda function, `instance-scheduler-dev-schedulingRequestHandlerLam`, is repeatedly failing with the error message: 
```
"errorCode": "ResourceAlreadyExistsException",
"errorMessage": "The specified log stream already exists"
```
This issue began late Friday evening, causing the Lambda function to be triggered infinitely, with each execution failing with the same error.

**To Reproduce**

1. Deploy Instance Scheduler v3.0.0 in the `ap-southeast-2` region.
2. Monitor the Lambda function `instance-scheduler-dev-schedulingRequestHandlerLam`.
3. Observe the CloudTrail logs to see multiple CreateLogStream calls by instance-scheduler-dev-schedulingRequestHandlerLam. Check the details of these logs, and you will see the error indicating that the log stream already exists.

**Expected behavior**

The Lambda function should create a new log stream or write to an existing one without errors, and it should not enter an infinite loop of execution.

**Please complete the following information about the solution:**

- [x] Version: v3.0.0
- [x] Region: ap-southeast-2
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub? N/A
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? Yes
- [x] Were there any errors in the CloudWatch Logs? Yes
      [Troubleshooting](https://docs.aws.amazon.com/solutions/latest/instance-scheduler-on-aws/troubleshooting.html)

**Screenshots**
N/A

**Additional context**

The issue was not present immediately after upgrading to v3.0.0. It started occurring approximately 25 days later, suggesting that it may be related to a change or update on the AWS side. We have not made any modifications to the solution since upgrading.

**Comment by CrypticCabub** [comment]
Thanks for reporting this issue! Has this error been ongoing for multiple days or just one day? the log stream used by scheduling logic is supposed to be recreated every day with the logic checking if the stream already exists.

Also, is this error causing the lambda to fail, or are you just seeing the warning in cloud trail but not observing any impact to the solution itself? Within the logging code used by instance scheduler (https://github.com/aws-solutions/instance-scheduler-on-aws/blob/main/source/app/instance_scheduler/util/logger.py#L160-L165) there is an intentional write that is expected to raise a resource-already-exists exception as part of the normal flow of solution logging.

**Comment by sampreethamithkumar** [comment]
Thanks for getting back. 
We noticed this error on late Friday. When I reviewed the logs from a few days prior, I noticed the same error was being triggered every few seconds.  

I don't think this error is impacting the solution but got a bit concerned looking at the number of cloud trail events. 

I've attached a screenshot showing the number of error events captured in CloudTrail.
<img width="1696" alt="image" src="https://github.com/user-attachments/assets/52d22294-0be6-4bb6-9bcd-ec6a0d15036c">

**Comment by arkadiusz-koziel-nc** [comment]
These Events are caused by ApiCall, even if exception is handled.
Could You add checking if log stream exists? Something like that:

```
            try:
                response = client.describe_log_streams(
                    logGroupName=self._log_group,
                    logStreamNamePrefix=self._log_stream,
                    limit=1
                )
                
                log_stream_exists = any(log_stream['logStreamName'] == self._log_stream for log_stream in response['logStreams'])
                
                if not log_stream_exists:
                    # Create the log stream if it doesn't exist
                    self.client.create_log_stream(
                        logGroupName=self._log_group, logStreamName=self._log_stream
                    )
            except self.client.exceptions.ResourceAlreadyExistsException:
                pass
```
