### ISSUE TITLE
unable to parse cron expression when using named weekday of month

### ISSUE THREAD

**Issue by hamza-fareed** [aws-solutions/instance-scheduler-on-aws#573]
**Describe the bug**

Unable to create period for day of month e.g first Tuesday of month

**To Reproduce**

Fails : Could not parse as any form of cron expression: tues#1
scheduler-cli create-period  --stack AWS-Instance-Scheduler --name weekday-test --weekdays tues#1 --begintime 5:00 --endtime 7:00
Passes : 
scheduler-cli create-period --stack AWS-Instance-Scheduler --name weekday-test1 --weekdays 1#1 --begintime 5:00 --endtime 7:00

**Expected behavior**

periods to be created when using named day of month 

**Please complete the following information about the solution:**

scheduler-cli 3.0.4
(SO0030) instance-scheduler-on-aws v3.0.4
Occurs on 3.03 as well

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example,
_"(SO0030) instance-scheduler-on-aws v1.5.1"_. You can also find the version from
[releases](https://github.com/aws-solutions/instance-scheduler-on-aws/releases)

- [ ] Region: eu-west-1
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for
      the sevices this solution uses? No
- [ ] Were there any errors in the CloudWatch Logs? Instance scheduler was updated and had these named day periods already configured. Cloudwatch logs had unknown schedule errors and threw error about period cron expression : 
Could not parse as any form of cron expression: tues#1
      [Troubleshooting](https://docs.aws.amazon.com/solutions/latest/instance-scheduler-on-aws/troubleshooting.html)

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by aws-khargita** [comment]
Hi @hamza-fareed, thank you for opening this issue.

Currently, the weekday expression expects the weekday to be the full name of the day `Tuesday`, the 0 indexed number of that day `1`, or the **three** letter abbreviation of that day `tue`. Using the 4 letter abbreviation will unfortunately fail to parse with the current implementation.

Please try again using the expression `tue#1` and let me know if this solves your problem!

**Comment by aws-khargita** [comment]
Marking this as closed as the suggested day abbreviation should work. If there are any further issues please reopen.
