### ISSUE TITLE
Instance Scheduler Ignores Updated ASG Tag and Uses Previous Tag Value to Start/Stop Instances

### ISSUE THREAD

**Issue by sampreethamithkumar** [aws-solutions/instance-scheduler-on-aws#574]
**Describe the bug**

The instance-scheduler is using an outdated tag value to start and stop instances, even though a new tag has been applied to the ASG. The expected behavior is for the ASG to not start or stop instances based on the new tag value, but the old tag seems to still be in effect.

**To Reproduce**

1. Create an Auto Scaling Group (ASG) and apply an instance-scheduler tag to it.
2. Update the ASG with a new tag value that should prevent the instance from starting or stopping.
3. Observe that the ASG continues to start and stop the instance based on the previous tag value.

**Expected behavior**

After updating the tag, the ASG should not start or stop the instance based on the new tag value.

- [ ] Region: ap-southeast-2
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for
      the sevices this solution uses?: No
- [ ] Were there any errors in the CloudWatch Logs?: No

**Comment by sampreethamithkumar** [comment]
Hi @aws-khargita & @CrypticCabub ,

We are currently using 3.0.0

On Friday afternoon, we updated the parameter, but upon returning Monday morning, we noticed the instance had stopped at 7 PM on Friday and restarted at 6:30 AM on Monday, following the previous tag's behavior. This information was found in the ASG Activity tab. As a temporary fix, I manually deleted all the ASG scheduled actions.

**Comment by CrypticCabub** [comment]
We're there any other errors? I would recommend updating to 3.0.4 and checking if the error persists, as [the 3.0.1 release](https://github.com/aws-solutions/instance-scheduler-on-aws/releases/tag/v3.0.1) included a bug-fix for ASG schedules not being upgraded correctly when multiple ASGs were involved.

**Comment by sampreethamithkumar** [comment]
Apologies for the late reply. Sure, I will give that a try.

**Comment by sampreethamithkumar** [comment]
Updating to version 3.0.4 fixed the issue. Thanks for your help.
