### ISSUE TITLE
Support for OpenSearch on the roadmap?

### ISSUE THREAD

**Issue by stepkirk** [aws-solutions/instance-scheduler-on-aws#576]
**Describe the feature you'd like**

I have some users that are using Instance Scheduler for most of their service stack. They would like to shutdown OpenSearch over the weekend along with all the other services (EC2, AWS, RDS, etc). 

Do you have this on the roadmap?

**Comment by CrypticCabub** [comment]
hi @stepkirk 

My understanding is that OpenSearch does not have support for the concept of being "shut down", so do you have a proposal for how Instance Scheduler might be able to help reduce costs in this area?
