### ISSUE TITLE
Stack Created with no errors, Schedules and Periods created, but no EC2 instances seen to schedule 3.0.5

### ISSUE THREAD

**Issue by jeff2work** [aws-solutions/instance-scheduler-on-aws#581]
**Describe the bug**

Coming from 1.3, which did not upgrade. So I deployed the 3.0.5 Stack as New. No errors in last deployment and Updated the Stack to enable debug logging, which does not appear to do anything? DynamoDB has all entries for config, Period, Schedule. Schedule Tag on instances from previous implementation. There are no entries in the State Table and when the scheduler is invoked, it reads the schedules and periods, but nothing else occurs. I see no logs for InstanceScheduler3-schedulingRequestHandlerLambda and not daily logs for InstanceScheduler3-InstanceSchedulerMain. Not sure where to look.

**To Reproduce**

I did nothing other than deploying the stack and configuring my Schedules and Periods as previously defined.

**Expected behavior**

I only have ec2 instances enabled, expect instances to be stopped/started per schedule

**Please complete the following information about the solution:**

- [ 3.0.5] Version: [e.g. v1.0.0]

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example,
_"(SO0030) instance-scheduler-on-aws v3.0.5"_. You can also find the version from
[releases](https://github.com/aws-solutions/instance-scheduler-on-aws/releases)

- [us-west-1] Region: [e.g. us-east-1]
- [No, other than configuration settings] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [Yes, very minimal use on any of these services ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for
      the sevices this solution uses?
- [No, only lack of logs] Were there any errors in the CloudWatch Logs?
      [Troubleshooting](https://docs.aws.amazon.com/solutions/latest/instance-scheduler-on-aws/troubleshooting.html)

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**
The solution is deployed in a single region within a single account. The account is an Organization  main account, but I did not enable the hub, Organizations, accounts or regions, just the default of where it was installed.
[schedulingOrchestrationHandler.csv](https://github.com/user-attachments/files/17578814/schedulingOrchestrationHandler.csv)
[InstanceScheduler3-InstanceSchedulerMain.csv](https://github.com/user-attachments/files/17578816/InstanceScheduler3-InstanceSchedulerMain.csv)
[instancescheduler3-SchedulingOrchestrator.csv](https://github.com/user-attachments/files/17578817/instancescheduler3-SchedulingOrchestrator.csv)

**Comment by CrypticCabub** [comment]
Logs are available under {stack-name}-Scheduler-Logs, and you would be logging for logs from the SchedulingOrchestrator and SchedulingRequestHandler in this log group. The Lambda Logs themselves do not contain any useful info as the actual log data is being redirected into this central log group

**Comment by jeff2work** [comment]
No Request Handler logs. I redeployed the stack on 10/31. I have provided the InstanceScheduler and Orchestrator logs.

[SchedulingOrchestratorHandler-20241101.csv](https://github.com/user-attachments/files/17599914/SchedulingOrchestratorHandler-20241101.csv)
[InstanceScheduler-20241031.csv](https://github.com/user-attachments/files/17599915/InstanceScheduler-20241031.csv)
[SchedulingOrchestratorHandler-20241034.csv](https://github.com/user-attachments/files/17599916/SchedulingOrchestratorHandler-20241034.csv)

**Comment by CrypticCabub** [comment]
What is the configuration of your hub stack?
- do you have EC2 scheduling enabled?
- do you have hub account scheduling enabled?

**Comment by jeff2work** [comment]
Hi,

Hub stack is not enabled. One account, one region is all that is needed. The only scheduling enabled is ec2.

**Comment by CrypticCabub** [comment]
if you are trying to schedule the same account that the hub stack is installed in, schedule_hub_account must be enabled. otherwise it will be automatically filtered out of the account list

**Comment by jeff2work** [comment]
I updated to enable the hub account and it sees my instances now. The "hub" was throwing me off, never mentioned this on the previous releases. Thought it was only applicable to the Orgs config. I appreciate the direction.

**Comment by jeff2work** [comment]
Resolved by enabling hub account

**Comment by CrypticCabub** [comment]
glad that worked. I believe the parameter was named "schedule_lambda_account" in older versions but at some point it was renamed to match the more standard "hub-spoke" naming model typically used by AWS Solutions.
