### ISSUE TITLE
CN - SpokeRegistration Lambda - Policy statements for AWS organisation 

### ISSUE THREAD

**Issue by paulbaudrier** [aws-solutions/instance-scheduler-on-aws#584]
**Describe the bug**

In the CN (China) variant of the AWS instance scheduler, the scheduler’s main stack creates a Lambda function "SpokeRegistration" along with an associated IAM role. 
Normally, the policy associated with the role is configured to use the AWS Organization ID rather than a wildcard "*" using condition. 
However, in China regions, the policy appears to default to "*", even though it's not explicitly specified as such. 
This could lead to unintended access permissions without raising any error.

**To Reproduce**

Deploy the China-specific (CN) template for the Instance Scheduler solution in a China region (e.g., cn-north-1) with AWS Organization "active".
Observe the creation of the Lambda function "SpokeRegistration" and associated IAM role in the stack.
Note that the policy behaves using a wildcard "*" rather than the AWS Organization ID.

**Expected behavior**

The policy should respect the AWS Organization ID when AWS Organisation is active on template.

**Please complete the following information about the solution:**

 Version: [v1.5.1]
 Region: [cn-north-1]
 Was the solution modified from the version published on this repository? No
 If the answer to the previous question was yes, are the changes available on GitHub? N/A
 Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? Yes
Were there any errors in the CloudWatch Logs? No, but the policy defaults to "*" implicitly.

**Screenshots**

N/A

**Additional context**

N/A

**Comment by CrypticCabub** [comment]
Thanks for reporting this issue. we will investigate further and add a fix to our backlog as soon as we can repduce the error

**Comment by paulbaudrier** [comment]
@CrypticCabub I confirm the version used was 3.0.6.
Also tested on 3.0.7 with same behavior

**Comment by CrypticCabub** [comment]
Thank you for bringing the issue to our attention. Previously, the use of aws:PrincipalOrgId in AWS Lambda resource policies was supported only in other AWS global regions, but not CN-NORTH-1 and CN-NORTHWEST-1 regions. However, as of November 23, 2024, we have rolled out support for using aws:PrincipalOrgId key in Lambda resource policies for CN-NORTH-1 and CN-NORTHWEST-1 Regions. The policies will work as they do in other regions. 

we recommend you disable and re-enable AWS Organizations mode on your deployed hub stack to redeploy the affected policy. Please make sure to NOT remove your PrincipalOrgID from the "Principals" parameter, or you will update the Config record and lose previously registered accounts. 

The following is a list of the recommended steps:

Navigate to the CloudFormation console of the account containing the hub stack for the impacted version of Instance Scheduler (V3.0.0 - V3.0.7 deployed before November 23, 2024.

Select the deployed hub stack from the stack list and choose the "Update" option.

On the next screen labeled "Update Stack", select the option to "Use existing template" and click next.

On the next screen labeled "Specify stack details", the parameter labeled "Use AWS Organizations" will be set to "Yes". You will need to update the CloudFormation parameter labeled "Use AWS Organizations" to the value "No". You should not need to change any other parameters. Click next to navigate to the next screen.

On the next screen labeled "Configure stack options", click the check box at the bottom acknowledging the required capabilities and click next.

On the next screen labeled "Review <your stack name>", make sure the updated CloudFormation parameter is appearing as "No" and then click submit.

You will now need to wait for the stack update to complete. You will know it is done when the status of the stack is "UPDATE_COMPLETE".

Repeat the previous steps, this time setting the "Use AWS Organizations" parameter back to "Yes". This will cause the Lambda Resource Policy to be recreated with the fixed conditional statement, restricting lambda invocations to principals within the organization.

Once the update is complete, navigate to the lambda function named InstanceScheduler-<YOUR_NAMESPACE>-SpokeRegistration and check that the Resource-based policy statements section contains a statement restricting permission to the PrincipalOrgId of your organization. You can view these by selecting the "Configuration" tab in the Lambda Function console, selecting the "Permissions" section in the sidebar, and scrolling to the bottom of that page where you will see a section labeled "Resource-based policy statements".

If you have questions, please contact AWS Support at https://console.aws.amazon.com/support/
